[package]
name = "errorpal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
imara-diff = "0.1.5"
regex = "1.10.2"
thiserror = "1.0.50"
